<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <!-- Logo que redirige al index -->
    <a class="navbar-brand" href="index.php">
      <img
        src="codes/img/logo.png"
        alt="Logo"
        width="40"
        height="40"
        class="d-inline-block align-text-top"
      />
      CCSS Orotina-San Mateo
    </a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
