<!-- Pie de página -->
<footer class="bg-light text-center text-lg-start mt-auto py-3">
  <div class="container">
    <span class="text-muted"
      >© 2024 Caja Costarricense del Seguro Social. Todos los derechos
      reservados.</span
    >
    <br />
    <span class="text-muted">Página creada por Caleb Rodriguez Cordero.</span>
  </div>
  <script src="codes/js/bootstrap.bundle.min.js"></script>
  <!-- JS de Bootstrap -->
  <!-- Tu archivo JS -->
</footer>

<script src="codes/js/bootstrap.bundle.min.js"></script>
<!-- JS de Bootstrap -->
<!-- Tu archivo JS -->
